{% set name = "raiutils" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/raiutils-{{ version }}.tar.gz
  sha256: 1686dfae2ed59ccadb69ce5957b753be352ead42e87559c24223c3dfd055b703

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - pandas
    - python >=3.6
    - requests
    - scikit-learn
    - scipy

test:
  imports:
    - raiutils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/responsible-ai-widgets
  summary: Common basic utilities used across various RAI tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janjagusch
    - bgalvao
